### ISSUE TITLE
[ BUG ] Error in changing theme

### ISSUE THREAD

**Issue by xerxiastudios** [mrzachnugent/react-native-reusables#118] opened 2024-03-29 01:39 UTC
<img width="1131" alt="Screenshot 2024-03-29 at 7 07 56 AM" src="https://github.com/mrzachnugent/react-native-reusables/assets/70348240/3beb5fd9-8502-4cea-87dc-240304fd043f">

An error using the starter app and clicking update button.

**Comment by mrzachnugent** [comment] 2024-03-29 11:49
@xerxiastudios Can you provide more information as I am not able to reproduce?

This could be a [`NativeWind`](https://github.com/marklawlor/nativewind/issues) issue. I remember having something similar happen when I had both the web and the iOS version running at the same time.

If you only get this error with web and iOS running at the same time, please close this issue and make a new one in the NativeWind repo.

If it happens when you only have the iOS app running, please provide a minimal reproduction repo so that I can also see this warning.

**Comment by xerxiastudios** [comment] 2024-03-31 04:57
Happens when both ios and web is running.

**Closed** 2024-03-31 04:57 UTC
Labels: bug
