### ISSUE TITLE
[ BUG ] 'onPress' prop does not fire when dropdown items are pressed

### ISSUE THREAD

**Issue by tctrautman** [mrzachnugent/react-native-reusables#122] opened 2024-04-02 20:01 UTC
**Describe the bug**

The (native only) `Dropdown Menu` component doesn't fire `onPress` callbacks that are provided to as props to the `DropdownMenuItem` children.

**To Reproduce**
1. Follow the manual instructions for setting up a dropdown-menu component.  When setting up the dropdown-menu primitive, use the native only option.
2. Start an iOS simulator
3. Use the below minimal implementation of the component & notice that the log isn't ever displayed when you press the item

```tsx
import * as React from 'react';
import { Button } from '~/components/ui/button';
import { MenuIcon } from '~/components/icons';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '~/components/ui/dropdown-menu';
import { Text } from '~/components/ui/text';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export const Dropdown = () => {
  const [open, setOpen] = React.useState(false);
  const insets = useSafeAreaInsets();
  const contentInsets = {
    top: insets.top,
    bottom: insets.bottom,
    left: 12,
    right: 12,
  };

  return (
    <DropdownMenu
      open={open}
      onOpenChange={(newVal) => {
        setOpen(newVal);
      }}
    >
      <DropdownMenuTrigger asChild>
        <Button variant="link">
          <MenuIcon className="text-foreground -mr-2 -mt-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        insets={contentInsets}
        className="w-64 native:w-72 border border-primary"
      >
        <DropdownMenuItem onPress={() => console.log('onPress fired')}> // This is the meaningful line
          <Text>fire onPress</Text>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
```

**Expected behavior**
When using the above component I would expect that a log of `onPress fired` would be shown when item is pressed.

**Platform**
 - Type: Simulator
 - OS: iOS

**Additional context**
As noted in another issue, this project is awesome -- thanks for building it!

**Comment by mrzachnugent** [comment] 2024-04-07 13:50
@tctrautman Thank you!

Unfortunately I am not able to recreate this issue so I will close this issue. I tried in the this repositories showcase app and in a new project and they both work.

There were come updates to the CLI since this issue was created. Perhaps you could delete your dropdown-menu `ui` and `primitive` files and try again by adding it to your project with: `npx @react-native-reusables/cli@latest add dropdown-menu`

If you still have this issue after trying with the CLI, please open a new issue with a minimal reproduction issue so that I help resolve it.

**Closed by mrzachnugent** 2024-04-07 13:50 UTC
Labels: bug

**Comment by tctrautman** [comment] 2024-04-08 18:25
Using the updated CLI command seems to have fixed the issue -- thanks, @mrzachnugent!

**Comment by asopromadze** [comment] 2024-09-27 09:23
I have same issue
``` jsx
 <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button size="icon" variant="outline">
          <Text>open</Text>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuItem
          closeOnPress
          onPress={() => {
            console.log("pressed");
            // navigation.navigate("profile");
          }}
        >
          <UserRoundCog size={20} />
          <TextView text="profile" />
        </DropdownMenuItem>
        <DropdownMenuItem closeOnPress>
          <LogOut size={20} />
          <TextView text="logOut" />
        </DropdownMenuItem>
      </DropdownMenuContent>
 </DropdownMenu>      
```
#### Platform
     Type: Device
     OS:  Android
